config/routes.rb
Reflect::Application.routes.draw do
  root to: "home#index"

  get "dashboard/comparison" => "dashboard#comparison"
  get "dashboard/days" => "dashboard#days"
  post "day/create" => "day#create"
  get "dashboard/index" => "dashboard#index"
  get "dashboard/profile" => "dashboard#profile"
  get "dashboard/comparison" => "dashboard#comparison"

  devise_for :users

  resources :traits

  resources :counter

  

end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :day_trait
	has_many :traits, :through => :day_trait
	belongs_to :users
end

app/models/day_trait.rb
class DayTrait < ActiveRecord::Base
	belongs_to :day
	belongs_to :trait

end

app/models/trait.rb
class Trait < ActiveRecord::Base

  has_many :trait_user
  has_many :users, :through => :trait_user

  has_many :day_trait
  has_many :days, :through => :day_trait
end

app/models/trait_user.rb
class TraitUser < ActiveRecord::Base
	belongs_to :trait
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trait_user
  has_many :traits, :through => :trait_user
  has_many :days

  def ctraituserfind
  	@findtraituser = Trait.find(n.id).trait_user.first.counter
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
 def after_sign_in_path_for(user)
 	@datenow = DateTime.now
    @datecreate = Day.find_or_create_by(:currentnow => @datenow.strftime("%d/%m/%Y"), :user_id => current_user.id) 
    return dashboard_index_path
  end
end

app/controllers/counter_controller.rb
class CounterController < ApplicationController

def create

	currentuserid = current_user.id
	daytraitid = DayTrait.find(params[:daytrait_id])
	daytraitid.icounter += 1
	daytraitid.save
	pi_trait_id = daytraitid.trait.id
	hazbolah = Trait.find(pi_trait_id)
	hazbolah.gcounter += 1
	hazbolah.save
	hazbolah2 = TraitUser.first(:conditions => ["trait_id = #{pi_trait_id} AND user_id = #{current_user.id}"])
	hazbolah2.counter += 1
	hazbolah2.save

    respond_to do |format|
      format.js   
   	end
   	
  end

  def index
  	@countershow = TraitUser.find(params[current_user.id])
  end

 end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def days
      dayclicked = params[:day_id]
      @daytrait = DayTrait.where(day_id: params[:day_id])
      @day2 = Day.first(:conditions => ["id = #{dayclicked} AND user_id = #{current_user.id}"])
      @clickeddate = @day2.id
      cookies[:nday_id] = @clickeddate
      cookies[:nday_id] || []
      respond_to do |format|
        format.js   
   	end
  end	

  def index
  	@usertrait = current_user.traits.all
   	@daysall = current_user.days.all
    @traitexistence=TraitUser.where(user_id: current_user.id)
  end

  def profile
  end

  def comparison
  end
  
end

app/controllers/day_controller.rb
class DayController < ApplicationController

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController
  def index
        deletionid = params[:id]
        @clickedalreadydate = cookies[:nday_id]
        @daytrait = DayTrait.first(:conditions => ["id = #{deletionid} AND day_id = #{@clickedalreadydate}"]) 
        @daytrait.destroy
      respond_to do |format|
        format.js
      end
  end

  def create
    @clickedalreadydate = cookies[:nday_id]
  	@trait = Trait.find_or_create_by(name: params[:trait][:name].downcase)
    TraitUser.find_or_create_by(:user_id => current_user.id, :trait_id => @trait.id)
    DayTrait.find_or_create_by(:day_id => @clickedalreadydate, :trait_id => @trait.id) 
    respond_to do |format|
      format.js
    end
  end

  def new
  end

  def edit	
  end

  def show
  end

  def update
  end

  def delete

  end

  def trait_params
  	params.require(:trait).permit(:name)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counter_helper.rb
module CounterHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/day_helper.rb
module DayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trait_helper.rb
module TraitHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/counter/_alltrait.html.erb
   		<% @clickedalreadydate = cookies[:nday_id] %>
<% @daytrait =	 DayTrait.where(day_id: @clickedalreadydate) %>
		<% today =	 Day.find(@clickedalreadydate).currentnow %>
		<h3 id = "date-proclaim"> <i class="fi-marker"></i> <%= today %> </h3>
		<h4 class = "date-header">
		</h4>
<% @daytrait.each do |t| %>
		<div class ="large-4 columns trait_list">
			<%= link_to "#{t.trait.name} #{DayTrait.first(:conditions => ["trait_id = #{t.trait_id} AND id = #{t.id}"]).icounter} Times" , counter_index_path(:daytrait_id => t),remote: true, method: :POST %>
			<%= link_to (raw("<i class='fi-prohibited'></i>")),traits_path(:id => t),remote: true %>
			<div class= "row">
				<div class="large-12 columns">					
				</div>
			</div>
		</div>
<% end %>

<br>
<br>
	<div class ="large-12 columns trait_box">
		<%= form_for :trait, :url=>traits_path, :method=> :POST, remote: true, html: {id: "add_trait_form", } do |f| %>
		  Add a Trait: <%= f.text_field :name, :placeholder => "Add something you do here!", class:"form_text_field" %>
		<%= f.submit 'Add it!', class: "button prefix", id: "formid" %>
		<% end %>
	</div>

app/views/counter/create.js.erb
$('.wrapper_trait').html("<%= escape_javascript(render :partial => 'alltrait', :locals => { :f => @daytrait } ) %>");
  	$('.trait_list').each(function(){
  		$(this).click(function(e){
  		if(e.target === this) {
  	  $(this).find(".fi-prohibited").fadeToggle();
  			}
  		})
  	})

app/views/counter/index.js.erb
$('.wrapper_trait').html("<%= escape_javascript(render :partial => 'alltrait', :locals => { :f => @daytrait } ) %>");
    $('.trait_list').each(function(){
      $(this).click(function(e){
      if(e.target === this) {
      $(this).find(".fi-prohibited").fadeToggle();
        }
      })
    $('#notsidebar').slimScroll({
      height: '700px',
      start: 'bottom',
      railVisible: 'true'
  });

app/views/dashboard/_alltrait.html.erb
<% @daytrait =	 DayTrait.where(day_id: params[:day_id]) %>
		<% today =	 Day.find(params[:day_id]).currentnow %>
		<h3 id = "date-proclaim"> Date Selected: <%= today %> </h3>
		<h4 class = "date-header">
		</h4>
<% @daytrait.each do |t| %>
		<div class ="large-4 columns trait_list">
			<%= link_to "#{t.trait.name} #{DayTrait.first(:conditions => ["trait_id = #{t.trait_id} AND id = #{t.id}"]).icounter} Times" , counter_index_path(:daytrait_id => t), method: :POST %>
			<%= link_to (raw("<i class='fi-prohibited'></i>")),traits_path(:id => t), {:class => "icon-white"} %>
			<div class= "row">
				<div class="large-12 columns">					
				</div>
			</div>
		</div>
<% end %>

app/views/dashboard/comparison.html.erb
<script type="text/javascript" charset="utf-8">
$(function () {
        $('#guailan').highcharts({
            chart: {
                type: 'spline'
            },
            title: {
                text: 'Activities across all time'
            },
            subtitle: {
                text: 'A factual reflection of you'
            },
            xAxis: {
                type: 'datetime',
                dateTimeLabelFormats: { // don't display the dummy year
                    month: '%e. %b',
                    year: '%b'
                }
            },
            yAxis: {
                title: {
                    text: 'Frequency'
                },
                min: 0
            },
            tooltip: {
                formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                        Highcharts.dateFormat('%e. %b', this.x) +': '+ this.y + ' times';
                }
            },
            
            series: [
<% @predatacycle = DayTrait.joins(:day).where(days: {user_id: current_user.id}) %>
<% @datacycle = @predatacycle.all.group_by{ |t| t.trait_id} %>
<% @datacycle.each do |n,p| %>
{name:
"<%= Trait.find(n).name %>",
data:[
<% p.each do |k| %>
[Date.UTC(<%= k.created_at.strftime("%Y, %m, %d") %>), <%= k.icounter %>],
<% end %>
]
},
<% end %>
]
        });
    });
</script>




<div class="row">
    <div class= "large-12 columns">
        <h1 style="text-align:center"> Here's a reflection of you. </h1>
    </div>
</div>

<div id = "guailan" style="width:80%;margin:auto;"></div>

app/views/dashboard/days.js.erb
$('.wrapper_trait').html("<%= escape_javascript(render :partial => 'alltrait', :locals => { :f => @daytrait } ) %>");
  	$('.trait_list').each(function(){
  		$(this).click(function(e){
  		if(e.target === this) {
  	  $(this).find(".fi-prohibited").fadeToggle();
  			}
  		})
  	$('#notsidebar').slimScroll({
	    height: '700px',
	    start: 'bottom',
	    railVisible: 'true'
	});
  	})

app/views/dashboard/index.html.erb
<div class="row">
	<div class="wrapper_trait">
		<div class= "row">				
			<% if @traitexistence.empty? %>
				<br><br>
					<h1 style="text-align:center;">Hi there!</h1>	
					<p class="content" style="text-align:center;" > Welcome! You seem to not have anything tracked so let's get you started.</p>
					<h1 style="text-align:center;">Where to go?</h1>	
					<p class="content" style="text-align:center;" > Click on the date on the left to get started (the date should be today). Add a trait to begin.</p>
					<h1 style="text-align:center;font-size:80px;padding-bottom:0px">Tips.</h1>
					<h5 style="text-align:center;position:relative;bottom:40px; "> Which means read this, it's super important</h5>	
					<div class="row">
						<div class="large-12 columns">
							<p class="content" style="text-align:center; font-family:wonder;" >1. Come back here once you've added a trait</p>
							<p class="content" style="text-align:center; font-family:wonder;" >2. Add traits of the same name if you do it across days. It helps the graph.</p>
							<p class="content" style="text-align:center; font-family:wonder;" >3. Graph is located on the top bar as graph icon.</p>	
						</div>
					</div>
				<% else %>
				<div class="large-12 columns">
					<h1 id ="welcome"> At a glance. </h1>
				</div>
				<div class="row">
					<div class="large-4 columns">
						<div class="big-icons">
							<i class="fi-results-demographics"></i>
							<p class="content"> You've logged in <b><%= current_user.sign_in_count %> times</b> so far!</p>
						</div>
					</div>
					<div class="large-4 columns">
						<div class="big-icons">
							<i class="fi-foot"></i>
							<p class="content"> You've tracked <b><%= TraitUser.where(user_id: current_user.id).count %> different</b> things about yourself! </p>
						</div>
					</div>
					<div class="large-4 columns">
						<div class="big-icons">
							<i class="fi-plus"></i>
							<p class="content"> You've tracked yourself <b> <%= TraitUser.sum(:counter, :conditions => {:user_id => current_user.id}) %> times! </b>  </p>
						</div>
					</div>
					<div class="row">
						<div class="large-12 columns">
							<div class="big-icons">
								<i class="fi-paw"></i>
								<p class="content"> Your tracks for <b style="font-family:wonder;">"<%= TraitUser.where(user_id: current_user.id).order(counter: :desc).first.trait.name  %>"</b> are the highest at <b><%= TraitUser.maximum(:counter, :conditions => {:user_id => current_user.id})  %> times!</b>  </p>

							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>		
</div>

<br>
<br>
<div class= "row">

<div class="side_bar">
	<div id="notsidebar">
		<% @daysall.each do |n| %>
			<%= link_to "#{n.currentnow}" , dashboard_days_path(:day_id => n), remote: true, :class => "replacemiddle" %> <br>
		<% end %>
	</div>
</div>

app/views/dashboard/index.js.erb
$('.wrapper_trait').html("<%= escape_javascript(render :partial => 'alltrait', :locals => { :f => @daytrait } ) %>");
    $('.trait_list').each(function(){
      $(this).click(function(e){
      if(e.target === this) {
      $(this).find(".fi-prohibited").fadeToggle();
        }
      })
    $('#notsidebar').slimScroll({
      height: '700px',
      start: 'bottom',
      railVisible: 'true'
  });

app/views/dashboard/profile.html.erb
<div class = "row">
	<div class="large-12 columns">
<h2>Profile</h2>
<p>Email: <%= current_user.email %></p>
<p>Sign-in-count: <%= current_user.sign_in_count %></p><br>
</div>
</div>

app/views/home/index.html.erb
<div class="wrapper">
	<div class="row">
		<div class="small-12 columns" >
			<p class="logofont" id="cheesycopycat"> reflect </p>
			<h2 id="cheesytext">Helping you be the person you've always wanted to be</h2>	
		</div>
	</div>
	<div class="background">
		&nbsp;
	</div>
</div>
<div class="shift">
	<div class="row ">
		<div class="large-12 columns">
			<h1 id="cheesyhead">Reflect tracks what you do.</h1>
		</div>
		<div class="large-12 columns content">
			 <p>Reflect is a tracking webapp built by an intern at Zett Pte. Ltd. Reflect was concepted under the influence of a gentlemen's wager and is therefore a webapp that has consumed much of the intern's time. That being the case, the intern is highly dedicated to Reflect. Feel free to leave your money here, in safe hands.<br><br>

			 Reflect aims to give you an overview of your life. Essentially, it's built around the premise of characterising you. The user.</p>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
	    	<h1 id="cheesyhead">Track...what exactly?</h1>
	    </div>
	    <div class="grid-icon-wrapper">
	    	<div class="large-4 columns content">
	    		 <div class="big-icons">
				 <i class="fi-torsos-all"></i>
				</div>
				 <p>Track how many times you talked to a friend</p>
			</div>
	    	<div class="large-4 columns content">
	    		 <div class="big-icons">
				 <i class="fi-music"></i>
				</div>
				 <p>See how many times you've listened to a song</p>
			</div>
			<div class="large-4 columns content">
	    		 <div class="big-icons">
				 <i class="fi-wrench"></i>
				</div>
				 <p>Find out the amount of hours you've spent on work</p>
			</div>
			<div class="large-4 columns content">
	    		 <div class="big-icons">
				 <i class="fi-guide-dog"></i>
				</div>
				 <p>Perhaps you want to track the amount of animals in your area</p>
			</div>
			<div class="large-4 columns content">
	    		 <div class="big-icons">
				 <i class="fi-heart"></i>
				</div>
				 <p>Maybe you need to know how many relationships you've been in</p>
			</div>
			<div class="large-4 columns content">
	    		 <div class="big-icons">
				 <i class="fi-social-youtube"></i>
				</div>
				 <p>Or the amount of hours you've spent procrastinating</p>
			</div>
			<div class="row">
				<div class="large-12 columns content">
					<div class="large-4 columns content">
			    		 <div class="big-icons">
						 <i class="fi-web"></i>
						</div>
					</div>	
					<div class="large-8 columns content centerheight">
						<h6> The idea is to track anything you want, for any situation.</h6>
					</div>
				</div>
			</div>
		</div>      
	</div>
	<div class="row">
		<div class="large-12 columns">
	    	<h1 id="cheesyhead">Why track?</h1>
	    </div>
    	<div class="large-12 columns content">
			 <p>Tracking everything you do lets you find out what kind of person you are, and where you should improve on. Here's how we do it.</p><br><br>
		</div>  
	</div> 
	<div class="row">
		<div class="large-4 columns content">
			<div class="big-icons">
				<i class="fi-checkbox"></i>
			</div>
		</div>
		<div class="large-8 columns content centerheight">
			<p>Simply add  a trait to track and click it on your dashboard to add.</p>
		</div>
	</div>
	<div class="row">
		<div class="large-4 columns content">
			<div class="big-icons">
				<i class="fi-graph-horizontal"></i>
			</div>
		</div>
		<div class="large-8 columns content centerheight">
			<p>Easy to read graphs gives you a quick overview.</p>
		</div>
	</div>
	<div class="row">
		<div class="large-4 columns content">
			<div class="big-icons">
				<i class="fi-lightbulb"></i>
			</div>
		</div>
		<div class="large-8 columns content centerheight">
			<p>We'll try to tell you how to make your life better.</p>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
	    	<h1 id="cheesyhead">What money?</h1>
	    </div>
    	<div class="large-12 columns content">
			 <p>Reflect will be a free service for as long as possible. That doesn't mean that we don't need any money to maintain the webapp. We'll be accepting donations for the maintainence of the webapp. Any excess funds will go to charitable organizations such as:</p>
		</div>    
	</div>
	<div class="row">
		<div class="large-3 columns">
			<%= image_tag("org1.jpg", :alt => "organization1") %>
		</div>
		<div class="large-3 columns centerheight">
			<%= image_tag("org2.gif", :alt => "organization2") %>
		</div>
		<div class="large-3 columns centerheight">
			<%= image_tag("org3.png", :alt => "organization3") %>
		</div>
		<div class="large-3 columns">
			<%= image_tag("org4.gif", :alt => "organization4") %>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
	    	<h1 id="cheesyhead">Who are you?</h1>
	    </div>
    	<div class="large-12 columns content">
			 <p>I'm Isaac. Founder of Zett Pte. Ltd. And also the sole intern and employee of the company. We're a startup company that are aiming to disrupt the way vendors treat people who queue up. We find that standing in a line is probably one of the least efficient ways to do things.<br><br>

			 I'm trying out Reflect as a way to test whatever i've learnt across the past 2 months of learning coding. So, if you're interested in trying out the fruits of my labour, do click the button below.</p>
		</div>    
	</div>
	<div class="row">
		<div class = "large-12 columns content">
			<%= link_to("Try it",new_user_registration_path, html_options = {class: "button", id: "tryitbutton"}) %>
		</div>
	</div>		
</div>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Reflect" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "foundation-icons" %>
	<%= stylesheet_link_tag   "application" %>
	<%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
</head>


<body class="app">
  <div class="f-row">
        <nav class="top-bar">
          <div class="row">
            <div class="large-3 columns">
              <p>
                <% if user_signed_in? %>
                  <%= link_to "reflect", dashboard_index_path %>
                <% else %>
                  <%= link_to "reflect", root_path %>
                <% end %>
              </p>
            </div>
            <div class="large-9 columns" id="loginbar">
              <% if user_signed_in? %>
                <%= link_to (raw("<i class='fi-graph-bar' id = 'graphbar'></i>")) ,dashboard_comparison_path %>
                Signed in as <%= link_to "#{current_user.email}", dashboard_profile_path %> Not you?
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "sign in", new_user_session_path %>
              <% end %>
            </div>
          </div> 
        </nav>
  </div>
      <div class="row cancelmargin">
        <div class="large-3 columns">
          &nbsp;
        </div>
        <div class="large-6 columns">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}", :class =>"kill" %>
          <% end %>
        </div>
        <div class="large-3 columns">
          &nbsp;
        </div>
      </div>
      <%= yield %>
</body>

app/views/traits/_alltrait.html.erb
   		<% @clickedalreadydate = cookies[:nday_id] %>
<% @daytrait =	 DayTrait.where(day_id: @clickedalreadydate) %>
		<% today =	 Day.find(@clickedalreadydate).currentnow %>
		<h3 id = "date-proclaim"> <i class="fi-marker"></i> <%= today %> </h3>
		<h4 class = "date-header">
		</h4>
<% @daytrait.each do |t| %>
		<div class ="large-4 columns trait_list">
			<%= link_to "#{t.trait.name} #{DayTrait.first(:conditions => ["trait_id = #{t.trait_id} AND id = #{t.id}"]).icounter} Times" , counter_index_path(:daytrait_id => t),remote: true, method: :POST %>
			<%= link_to (raw("<i class='fi-prohibited'></i>")),traits_path(:id => t),remote: true %>
			<div class= "row">
				<div class="large-12 columns">					
				</div>
			</div>
		</div>
<% end %>

<br>
<br>
	<div class ="large-12 columns trait_box">
		<%= form_for :trait, :url=>traits_path, :method=> :POST, remote: true, html: {id: "add_trait_form", } do |f| %>
		  Add a Trait: <%= f.text_field :name, :placeholder => "Add something you do here!", class:"form_text_field" %>
		<%= f.submit 'Add it!', class: "button prefix", id: "formid" %>
		<% end %>
	</div>

app/views/traits/create.js.erb
$('.wrapper_trait').html("<%= escape_javascript(render :partial => 'alltrait', :locals => { :f => @daytrait } ) %>");
  	$('.trait_list').each(function(){
  		$(this).click(function(e){
  		if(e.target === this) {
  	  $(this).find(".fi-prohibited").fadeToggle();
  			}
  		})
  	$('#notsidebar').slimScroll({
	    height: '700px',
	    start: 'bottom',
	    railVisible: 'true'
	});
  	})

app/views/traits/index.js.erb
$('.wrapper_trait').html("<%= escape_javascript(render :partial => 'alltrait', :locals => { :f => @daytrait } ) %>");
  	$('.trait_list').each(function(){
  		$(this).click(function(e){
  		if(e.target === this) {
  	  $(this).find(".fi-prohibited").fadeToggle();
  			}
  		})
  	})